In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
##A row vector x containing the first 12 integers starting with 0
x = np.arange(12)
px=torch.arange(12)
tx=tf.range(12)

In [3]:
print(x.shape)
print(px.shape)
print(tx.shape)

(12,)
torch.Size([12])
(12,)


In [4]:
#size
print(x.size)
print(px.numel)
print(tf.size(x))


12
<built-in method numel of Tensor object at 0x7f70b29ed990>
tf.Tensor(12, shape=(), dtype=int32)


In [5]:
#reshape
print(x.reshape(3,4))
print(px.reshape(3,4))
print(tf.reshape(x,(3,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int64)


we will want our matrices initialized either with zeros, ones, some other constants, or numbers randomly sampled from a specific distribution. We can create a tensor representing a tensor with all elements set to 0 and a shape of (2, 3, 4) as follows

In [6]:
print(np.zeros((2,3,4)))
print(np.ones((2,3,4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
print(torch.zeros((2,3,4)))
print(torch.ones((2,3,4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [8]:
print(tf.zeros((2,3,4)))
print(tf.ones((2,3,4)))

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


we want to randomly sample the values for each element in a tensor from some probability distribution
For example, when we construct arrays to serve as parameters in a neural network, we will typically initialize their values randomly
Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1.

In [9]:
print(np.random.normal(0,1, size=(3,4)))

[[-1.10308616 -1.64739034 -0.13406403  0.92388041]
 [ 0.51907089  2.01124759 -0.47938068 -1.72094364]
 [ 0.5348224   1.92025086 -0.2066009  -2.99242721]]


In [10]:
print(torch.randn(3,4))

tensor([[-0.2696,  1.0795, -0.4888, -0.6548],
        [-1.2332,  0.9966,  1.4060,  0.3325],
        [-0.7305, -1.6041,  1.0327,  0.1910]])


In [11]:
print(tf.random.normal(shape=[3,4]))

tf.Tensor(
[[ 0.83985883  3.017741    0.43423808 -2.186847  ]
 [-0.296071   -0.40643916 -0.72704726  1.3467112 ]
 [ 1.3694528   0.21670945 -0.8643489  -0.27682877]], shape=(3, 4), dtype=float32)


In [12]:
np.array([[2,3,4],[3,4,5],[4,5,6]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [13]:
torch.tensor([[2,3,4],[3,4,5],[4,5,6]])

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [14]:
tf.constant([[2,3,4],[3,4,5],[4,5,6]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]], dtype=int32)>

# Operations

In [15]:
nx = np.array([[1,2,3],[4,5,6]])
ny = np.array([[6,7,8],[9,8,5]])

In [16]:
print(nx*ny)
print(nx-ny)
print(nx+ny)
print(nx/ny)
print(nx**ny)

[[ 6 14 24]
 [36 40 30]]
[[-5 -5 -5]
 [-5 -3  1]]
[[ 7  9 11]
 [13 13 11]]
[[0.16666667 0.28571429 0.375     ]
 [0.44444444 0.625      1.2       ]]
[[     1    128   6561]
 [262144 390625   7776]]


In [17]:
px = torch.tensor([1.0, 2, 4, 8])
py = torch.tensor([2, 2, 2, 2])

In [18]:
print(px*py)
print(px-py)
print(px+py)
print(px/py)
print(px**py)

tensor([ 2.,  4.,  8., 16.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 3.,  4.,  6., 10.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


In [19]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y 

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

In [20]:
np.exp(nx)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [21]:
torch.exp(px)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [22]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

In [23]:
nx = np.arange(12).reshape(3,4)
ny = np.array([[1,2,3,1],[2,3,4,3],[4,5,6,7]])
np.concatenate([nx,ny],axis=0)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  1],
       [ 2,  3,  4,  3],
       [ 4,  5,  6,  7]])

In [24]:
np.concatenate([nx,ny],axis=1)

array([[ 0,  1,  2,  3,  1,  2,  3,  1],
       [ 4,  5,  6,  7,  2,  3,  4,  3],
       [ 8,  9, 10, 11,  4,  5,  6,  7]])

In [25]:
px = torch.arange(12).reshape(3,4)
py = torch.tensor([[1,2,3,1],[2,3,4,3],[4,5,6,7]])
torch.cat([px,py],axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  2,  3,  1],
        [ 2,  3,  4,  3],
        [ 4,  5,  6,  7]])

In [26]:
torch.cat([px,py],axis=1)

tensor([[ 0,  1,  2,  3,  1,  2,  3,  1],
        [ 4,  5,  6,  7,  2,  3,  4,  3],
        [ 8,  9, 10, 11,  4,  5,  6,  7]])

In [27]:
tx=tf.reshape(tf.range(12),(3,4))
ty=tf.constant([[1,2,3,1],[2,3,4,3],[4,5,6,7]])
tf.concat([tx,ty],axis=0)


<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  1],
       [ 2,  3,  4,  3],
       [ 4,  5,  6,  7]], dtype=int32)>

In [28]:
tf.concat([tx,ty],axis=1)

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  1,  2,  3,  1],
       [ 4,  5,  6,  7,  2,  3,  4,  3],
       [ 8,  9, 10, 11,  4,  5,  6,  7]], dtype=int32)>

In [29]:
nx==ny


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
tx==ty

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [31]:
## Summing all the elements in the tensor yields a tensor with only one element.
tf.reduce_sum(tx)

<tf.Tensor: shape=(), dtype=int32, numpy=66>

In [32]:
nx.sum()

66

In [33]:
px.sum()

tensor(66)

## Broadcasting Mechanism

In [34]:
na = np.arange(3).reshape(3,1)
nb = np.arange(2).reshape(1,2)
na,nb

(array([[0],
        [1],
        [2]]), array([[0, 1]]))

In [35]:
pa = torch.arange(3).reshape(3,1)
pb = torch.arange(2).reshape(1,2)
pa,pb

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [36]:
ta = tf.reshape(tf.range(3),(3,1))
tb = tf.reshape(tf.range(2),(1,2))
ta,tb

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [37]:
print(na+nb)
print(pa+pb)
print(ta+tb)

[[0 1]
 [1 2]
 [2 3]]
tensor([[0, 1],
        [1, 2],
        [2, 3]])
tf.Tensor(
[[0 1]
 [1 2]
 [2 3]], shape=(3, 2), dtype=int32)


## Indexing and Slicing

In [38]:
nx[-1], nx[1:3]

(array([ 8,  9, 10, 11]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [39]:
px[-1], py[1:3]

(tensor([ 8,  9, 10, 11]), tensor([[2, 3, 4, 3],
         [4, 5, 6, 7]]))

In [40]:
tx[-1], ty[1:3]

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[2, 3, 4, 3],
        [4, 5, 6, 7]], dtype=int32)>)

In [41]:
nx[1, 2] = 9
nx

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]])

In [42]:
px[1, 2] = 9

In [43]:
X_var = tf.Variable(tx)
X_var[1, 2].assign(9)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [44]:
nx[0:2, :] = 12
nx

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [ 8,  9, 10, 11]])

In [45]:
px[0:2,:]=12
px

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [46]:
tx = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
X_var = tf.Variable(tx)
X_var[0:2, :].assign(tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>